package fr.ralala.bleconnector.utils.gatt;

import android.util.SparseArray;

/**
 * Source: http://pci-ids.ucw.cz/v2.2/pci.ids
 */
public class UsbVendorName {
  private UsbVendorName() {

  }

  public static final SparseArray<String> VALUES = new SparseArray<String>();

  static {
    VALUES.put(0x0033, "Paradyne Corp.");
    VALUES.put(0x003D, "master");
    VALUES.put(0x0070, "Hauppauge Computer Works Inc.");
    VALUES.put(0x0100, "USBPDO-8");
    VALUES.put(0x0123, "General Dynamics");
    VALUES.put(0x0315, "SK - Electronics Co., Ltd.");
    VALUES.put(0x0402, "Acer aspire one");
    VALUES.put(0x046D, "Logitech Inc.");
    VALUES.put(0x0483, "UPEK");
    VALUES.put(0x04A9, "Canon");
    VALUES.put(0x04B3, "IBM");
    VALUES.put(0x04D9, "Filco");
    VALUES.put(0x04F2, "Chicony Electronics Co.");
    VALUES.put(0x051D, "ACPI\\VEN_INT&DEV_33A0");
    VALUES.put(0x0529, "Aladdin E-Token");
    VALUES.put(0x0553, "Aiptek USA");
    VALUES.put(0x058f, "Alcor Micro Corp.");
    VALUES.put(0x0590, "Omron Corp");
    VALUES.put(0x05ac, "Apple Inc.");
    VALUES.put(0x05E1, "D-MAX");
    VALUES.put(0x064e, "SUYIN Corporation");
    VALUES.put(0x067B, "Prolific Technology Inc.");
    VALUES.put(0x06FE, "Acresso Software Inc.");
    VALUES.put(0x0711, "SIIG, Inc.");
    VALUES.put(0x093a, "KYE Systems Corp. / Pixart Imaging");
    VALUES.put(0x096E, "USB Rockey dongle from Feitain");
    VALUES.put(0x0A5C, "Broadcom Corporation");
    VALUES.put(0x0A89, "BREA Technologies Inc.");
    VALUES.put(0x0A92, "Egosys, Inc.");
    VALUES.put(0x0AC8, "ASUS");
    VALUES.put(0x0b05, "Toshiba Bluetooth RFBUS, RFCOM, RFHID");
    VALUES.put(0x0c45, "Microdia Ltd.");
    VALUES.put(0x0cf3, "TP-Link");
    VALUES.put(0x0D2E, "Feedback Instruments Ltd.");
    VALUES.put(0x0D8C, "C-Media Electronics, Inc.");
    VALUES.put(0x0DF6, "Sitecom");
    VALUES.put(0x0E11, "Compaq Computer Corp.");
    VALUES.put(0x0E8D, "MediaTek Inc.");
    VALUES.put(0x1000, "LSI Logic");
    VALUES.put(0x1001, "Kolter Electronic - Germany");
    VALUES.put(0x1002, "Advanced Micro Devices, Inc.");
    VALUES.put(0x1003, "ULSI");
    VALUES.put(0x1004, "VLSI Technology");
    VALUES.put(0x1006, "Reply Group");
    VALUES.put(0x1007, "Netframe Systems Inc.");
    VALUES.put(0x1008, "Epson");
    VALUES.put(0x100A, "Ãâas Ltd. de Phoenix del ÃÆ de TecnologÃÆ");
    VALUES.put(0x100B, "National Semiconductors");
    VALUES.put(0x100C, "Tseng Labs");
    VALUES.put(0x100D, "AST Research");
    VALUES.put(0x100E, "Weitek");
    VALUES.put(0x1010, "Video Logic Ltd.");
    VALUES.put(0x1011, "Digital Equipment Corporation");
    VALUES.put(0x1012, "Micronics Computers Inc.");
    VALUES.put(0x1013, "Cirrus Logic");
    VALUES.put(0x1014, "International Business Machines Corp.");
    VALUES.put(0x1016, "Fujitsu ICL Computers");
    VALUES.put(0x1017, "Spea Software AG");
    VALUES.put(0x1018, "Unisys Systems");
    VALUES.put(0x1019, "Elitegroup Computer System");
    VALUES.put(0x101A, "NCR Corporation");
    VALUES.put(0x101B, "Vitesse Semiconductor");
    VALUES.put(0x101E, "American Megatrends Inc.");
    VALUES.put(0x101F, "PictureTel Corp.");
    VALUES.put(0x1020, "Hitachi Computer Electronics");
    VALUES.put(0x1021, "Oki Electric Industry");
    VALUES.put(0x1022, "Advanced Micro Devices");
    VALUES.put(0x1023, "TRIDENT MICRO");
    VALUES.put(0x1025, "Acer Incorporated");
    VALUES.put(0x1028, "Dell Inc.");
    VALUES.put(0x102A, "LSI Logic Headland Division");
    VALUES.put(0x102B, "Matrox Electronic Systems Ltd.");
    VALUES.put(0x102C, "Asiliant (Chips And Technologies)");
    VALUES.put(0x102D, "Wyse Technology");
    VALUES.put(0x102E, "Olivetti Advanced Technology");
    VALUES.put(0x102F, "Toshiba America");
    VALUES.put(0x1030, "TMC Research");
    VALUES.put(0x1031, "miro Computer Products AG");
    VALUES.put(0x1033, "NEC Electronics");
    VALUES.put(0x1034, "Burndy Corporation");
    VALUES.put(0x1036, "Future Domain");
    VALUES.put(0x1037, "Hitachi Micro Systems Inc");
    VALUES.put(0x1038, "AMP Incorporated");
    VALUES.put(0x1039, "Silicon Integrated Systems");
    VALUES.put(0x103A, "Seiko Epson Corporation");
    VALUES.put(0x103B, "Tatung Corp. Of America");
    VALUES.put(0x103C, "Hewlett-Packard");
    VALUES.put(0x103E, "Solliday Engineering");
    VALUES.put(0x103F, "Logic Modeling");
    VALUES.put(0x1041, "Computrend");
    VALUES.put(0x1043, "Asustek Computer Inc.");
    VALUES.put(0x1044, "Distributed Processing Tech");
    VALUES.put(0x1045, "OPTi Inc.");
    VALUES.put(0x1046, "IPC Corporation LTD");
    VALUES.put(0x1047, "Genoa Systems Corp.");
    VALUES.put(0x1048, "ELSA GmbH");
    VALUES.put(0x1049, "Fountain Technology");
    VALUES.put(0x104A, "STMicroelectronics");
    VALUES.put(0x104B, "Mylex / Buslogic");
    VALUES.put(0x104C, "Texas Instruments");
    VALUES.put(0x104D, "Sony Corporation");
    VALUES.put(0x104E, "Oak Technology");
    VALUES.put(0x104F, "Co-Time Computer Ltd.");
    VALUES.put(0x1050, "Winbond Electronics Corp.");
    VALUES.put(0x1051, "Anigma Corp.");
    VALUES.put(0x1053, "Young Micro Systems");
    VALUES.put(0x1054, "Hitachi Ltd");
    VALUES.put(0x1055, "Standard Microsystems Corp.");
    VALUES.put(0x1056, "ICL");
    VALUES.put(0x1057, "Motorola");
    VALUES.put(0x1058, "Electronics & Telecommunication Res");
    VALUES.put(0x1059, "Kontron Canada");
    VALUES.put(0x105A, "Promise Technology");
    VALUES.put(0x105B, "Mobham chip");
    VALUES.put(0x105C, "Wipro Infotech Limited");
    VALUES.put(0x105D, "Number Nine Visual Technology");
    VALUES.put(0x105E, "Vtech Engineering Canada Ltd.");
    VALUES.put(0x105F, "Infotronic America Inc.");
    VALUES.put(0x1060, "United Microelectronics");
    VALUES.put(0x1061, "8x8 Inc.");
    VALUES.put(0x1062, "Maspar Computer Corp.");
    VALUES.put(0x1063, "Ocean Office Automation");
    VALUES.put(0x1064, "Alcatel Cit");
    VALUES.put(0x1065, "Texas Microsystems");
    VALUES.put(0x1066, "Picopower Technology");
    VALUES.put(0x1067, "Mitsubishi Electronics");
    VALUES.put(0x1068, "Diversified Technology");
    VALUES.put(0x106A, "Aten Research Inc.");
    VALUES.put(0x106B, "Apple Inc.");
    VALUES.put(0x106C, "Hyundai Electronics America");
    VALUES.put(0x106D, "Sequent Computer Systems");
    VALUES.put(0x106E, "DFI Inc.");
    VALUES.put(0x106F, "City Gate Development LTD");
    VALUES.put(0x1070, "Daewoo Telecom Ltd.");
    VALUES.put(0x1071, "Mitac");
    VALUES.put(0x1072, "GIT Co. Ltd.");
    VALUES.put(0x1073, "Yamaha Corporation");
    VALUES.put(0x1074, "Nexgen Microsystems");
    VALUES.put(0x1075, "Advanced Integration Research");
    VALUES.put(0x1077, "QLogic Corporation");
    VALUES.put(0x1078, "Cyrix Corporation");
    VALUES.put(0x1079, "I-Bus");
    VALUES.put(0x107A, "Networth controls");
    VALUES.put(0x107B, "Gateway 2000");
    VALUES.put(0x107C, "Goldstar Co. Ltd.");
    VALUES.put(0x107D, "Leadtek Research");
    VALUES.put(0x107E, "Testernec");
    VALUES.put(0x107F, "Data Technology Corporation");
    VALUES.put(0x1080, "Cypress Semiconductor");
    VALUES.put(0x1081, "Radius Inc.");
    VALUES.put(0x1082, "EFA Corporation Of America");
    VALUES.put(0x1083, "Forex Computer Corporation");
    VALUES.put(0x1084, "Parador");
    VALUES.put(0x1085, "Tulip Computers Int'l BV");
    VALUES.put(0x1086, "J. Bond Computer Systems");
    VALUES.put(0x1087, "Cache Computer");
    VALUES.put(0x1088, "Microcomputer Systems (M) Son");
    VALUES.put(0x1089, "Data General Corporation");
    VALUES.put(0x108A, "SBS Operations");
    VALUES.put(0x108C, "Oakleigh Systems Inc.");
    VALUES.put(0x108D, "Olicom");
    VALUES.put(0x108E, "Sun Microsystems");
    VALUES.put(0x108F, "Systemsoft Corporation");
    VALUES.put(0x1090, "Encore Computer Corporation");
    VALUES.put(0x1091, "Intergraph Corporation");
    VALUES.put(0x1092, "Diamond Computer Systems");
    VALUES.put(0x1093, "National Instruments");
    VALUES.put(0x1094, "Apostolos");
    VALUES.put(0x1095, "Silicon Image, Inc.");
    VALUES.put(0x1096, "Alacron");
    VALUES.put(0x1097, "Appian Graphics");
    VALUES.put(0x1098, "Quantum Designs Ltd.");
    VALUES.put(0x1099, "Samsung Electronics Co. Ltd.");
    VALUES.put(0x109A, "Packard Bell");
    VALUES.put(0x109B, "Gemlight Computer Ltd.");
    VALUES.put(0x109C, "Megachips Corporation");
    VALUES.put(0x109D, "Zida Technologies Ltd.");
    VALUES.put(0x109E, "Brooktree Corporation");
    VALUES.put(0x109F, "Trigem Computer Inc.");
    VALUES.put(0x10A0, "Meidensha Corporation");
    VALUES.put(0x10A1, "Juko Electronics Inc. Ltd.");
    VALUES.put(0x10A2, "Quantum Corporation");
    VALUES.put(0x10A3, "Everex Systems Inc.");
    VALUES.put(0x10A4, "Globe Manufacturing Sales");
    VALUES.put(0x10A5, "Racal Interlan");
    VALUES.put(0x10A8, "Sierra Semiconductor");
    VALUES.put(0x10A9, "Silicon Graphics");
    VALUES.put(0x10AB, "Digicom");
    VALUES.put(0x10AC, "Honeywell IASD");
    VALUES.put(0x10AD, "Winbond Systems Labs");
    VALUES.put(0x10AE, "Cornerstone Technology");
    VALUES.put(0x10AF, "Micro Computer Systems Inc.");
    VALUES.put(0x10B0, "Gainward GmbH");
    VALUES.put(0x10B1, "Cabletron Systems Inc.");
    VALUES.put(0x10B2, "Raytheon Company");
    VALUES.put(0x10B3, "Databook Inc.");
    VALUES.put(0x10B4, "STB Systems");
    VALUES.put(0x10B5, "PLX Technology Inc.");
    VALUES.put(0x10B6, "Madge Networks");
    VALUES.put(0x10B7, "3Com Corporation");
    VALUES.put(0x10B8, "Standard Microsystems Corporation");
    VALUES.put(0x10B9, "Ali Corporation");
    VALUES.put(0x10BA, "Mitsubishi Electronics Corp.");
    VALUES.put(0x10BB, "Dapha Electronics Corporation");
    VALUES.put(0x10BC, "Advanced Logic Research Inc.");
    VALUES.put(0x10BD, "Surecom Technology");
    VALUES.put(0x10BE, "Tsenglabs International Corp.");
    VALUES.put(0x10BF, "MOST Corp.");
    VALUES.put(0x10C0, "Boca Research Inc.");
    VALUES.put(0x10C1, "ICM Corp. Ltd.");
    VALUES.put(0x10C2, "Auspex Systems Inc.");
    VALUES.put(0x10C3, "Samsung Semiconductors");
    VALUES.put(0x10C4, "Award Software Int'l Inc.");
    VALUES.put(0x10C5, "Xerox Corporation");
    VALUES.put(0x10C6, "Rambus Inc.");
    VALUES.put(0x10C8, "Neomagic Corporation");
    VALUES.put(0x10C9, "Dataexpert Corporation");
    VALUES.put(0x10CA, "Fujitsu Siemens");
    VALUES.put(0x10CB, "Omron Corporation");
    VALUES.put(0x10CD, "Advanced System Products");
    VALUES.put(0x10CF, "Fujitsu Ltd.");
    VALUES.put(0x10D1, "Future+ Systems");
    VALUES.put(0x10D2, "Molex Incorporated");
    VALUES.put(0x10D3, "Jabil Circuit Inc.");
    VALUES.put(0x10D4, "Hualon Microelectronics");
    VALUES.put(0x10D5, "Autologic Inc.");
    VALUES.put(0x10D6, "Wilson .co .ltd");
    VALUES.put(0x10D7, "BCM Advanced Research");
    VALUES.put(0x10D8, "Advanced Peripherals Labs");
    VALUES.put(0x10D9, "Macronix International Co. Ltd.");
    VALUES.put(0x10DB, "Rohm Research");
    VALUES.put(0x10DC, "CERN-European Lab. for Particle Physics");
    VALUES.put(0x10DD, "Evans & Sutherland");
    VALUES.put(0x10DE, "NVIDIA");
    VALUES.put(0x10DF, "Emulex Corporation");
    VALUES.put(0x10E1, "Tekram Technology Corp. Ltd.");
    VALUES.put(0x10E2, "Aptix Corporation");
    VALUES.put(0x10E3, "Tundra Semiconductor Corp.");
    VALUES.put(0x10E4, "Tandem Computers");
    VALUES.put(0x10E5, "Micro Industries Corporation");
    VALUES.put(0x10E6, "Gainbery Computer Products Inc.");
    VALUES.put(0x10E7, "Vadem");
    VALUES.put(0x10E8, "Applied Micro Circuits Corp.");
    VALUES.put(0x10E9, "Alps Electronic Corp. Ltd.");
    VALUES.put(0x10EA, "Tvia, Inc.");
    VALUES.put(0x10EB, "Artist Graphics");
    VALUES.put(0x10EC, "Realtek Semiconductor Corp.");
    VALUES.put(0x10ED, "Ascii Corporation");
    VALUES.put(0x10EE, "Xilinx Corporation");
    VALUES.put(0x10EF, "Racore Computer Products");
    VALUES.put(0x10F0, "Curtiss-Wright Controls Embedded Computing");
    VALUES.put(0x10F1, "Tyan Computer");
    VALUES.put(0x10F2, "Achme Computer Inc. - GONE !!!!");
    VALUES.put(0x10F3, "Alaris Inc.");
    VALUES.put(0x10F4, "S-Mos Systems");
    VALUES.put(0x10F5, "NKK Corporation");
    VALUES.put(0x10F6, "Creative Electronic Systems SA");
    VALUES.put(0x10F7, "Matsushita Electric Industrial Corp.");
    VALUES.put(0x10F8, "Altos India Ltd.");
    VALUES.put(0x10F9, "PC Direct");
    VALUES.put(0x10FA, "Truevision");
    VALUES.put(0x10FB, "Thesys Microelectronic's");
    VALUES.put(0x10FC, "I-O Data Device Inc.");
    VALUES.put(0x10FD, "Soyo Technology Corp. Ltd.");
    VALUES.put(0x10FE, "Fast Electronic GmbH");
    VALUES.put(0x10FF, "Ncube");
    VALUES.put(0x1100, "Jazz Multimedia");
    VALUES.put(0x1101, "Initio Corporation");
    VALUES.put(0x1102, "Creative Technology LTD.");
    VALUES.put(0x1103, "HighPoint Technologies, Inc.");
    VALUES.put(0x1104, "Rasterops");
    VALUES.put(0x1105, "Sigma Designs Inc.");
    VALUES.put(0x1106, "VIA Technologies, Inc.");
    VALUES.put(0x1107, "Stratus Computer");
    VALUES.put(0x1108, "Proteon Inc.");
    VALUES.put(0x1109, "Adaptec/Cogent Data Technologies");
    VALUES.put(0x110A, "Siemens AG");
    VALUES.put(0x110B, "Chromatic Research Inc");
    VALUES.put(0x110C, "Mini-Max Technology Inc.");
    VALUES.put(0x110D, "ZNYX Corporation");
    VALUES.put(0x110E, "CPU Technology");
    VALUES.put(0x110F, "Ross Technology");
    VALUES.put(0x1112, "Osicom Technologies Inc.");
    VALUES.put(0x1113, "Accton Technology Corporation");
    VALUES.put(0x1114, "Atmel Corp.");
    VALUES.put(0x1116, "Data Translation, Inc.");
    VALUES.put(0x1117, "Datacube Inc.");
    VALUES.put(0x1118, "Berg Electronics");
    VALUES.put(0x1119, "ICP vortex Computersysteme GmbH");
    VALUES.put(0x111A, "Efficent Networks");
    VALUES.put(0x111C, "Tricord Systems Inc.");
    VALUES.put(0x111D, "Integrated Device Technology Inc.");
    VALUES.put(0x111F, "Precision Digital Images");
    VALUES.put(0x1120, "EMC Corp.");
    VALUES.put(0x1121, "Zilog");
    VALUES.put(0x1123, "Excellent Design Inc.");
    VALUES.put(0x1124, "Leutron Vision AG");
    VALUES.put(0x1125, "Eurocore/Vigra");
    VALUES.put(0x1127, "FORE Systems");
    VALUES.put(0x1129, "Firmworks");
    VALUES.put(0x112A, "Hermes Electronics Co. Ltd.");
    VALUES.put(0x112C, "Zenith Data Systems");
    VALUES.put(0x112D, "Ravicad");
    VALUES.put(0x112E, "Infomedia");
    VALUES.put(0x1130, "Computervision");
    VALUES.put(0x1131, "NXP Semiconductors N.V.");
    VALUES.put(0x1132, "Mitel Corp.");
    VALUES.put(0x1133, "Eicon Networks Corporation");
    VALUES.put(0x1134, "Mercury Computer Systems Inc.");
    VALUES.put(0x1135, "Fuji Xerox Co Ltd");
    VALUES.put(0x1136, "Momentum Data Systems");
    VALUES.put(0x1137, "Cisco Systems Inc");
    VALUES.put(0x1138, "Ziatech Corporation");
    VALUES.put(0x1139, "Dynamic Pictures Inc");
    VALUES.put(0x113A, "FWB Inc");
    VALUES.put(0x113B, "Network Computing Devices");
    VALUES.put(0x113C, "Cyclone Microsystems Inc.");
    VALUES.put(0x113D, "Leading Edge Products Inc");
    VALUES.put(0x113E, "Sanyo Electric Co");
    VALUES.put(0x113F, "Equinox Systems");
    VALUES.put(0x1140, "Intervoice Inc");
    VALUES.put(0x1141, "Crest Microsystem Inc");
    VALUES.put(0x1142, "Alliance Semiconductor");
    VALUES.put(0x1143, "Netpower Inc");
    VALUES.put(0x1144, "Cincinnati Milacron");
    VALUES.put(0x1145, "Workbit Corp");
    VALUES.put(0x1146, "Force Computers");
    VALUES.put(0x1147, "Interface Corp");
    VALUES.put(0x1148, "Marvell Semiconductor Germany GmbH");
    VALUES.put(0x1149, "Win System Corporation");
    VALUES.put(0x114A, "VMIC");
    VALUES.put(0x114B, "Canopus corporation");
    VALUES.put(0x114C, "Annabooks");
    VALUES.put(0x114D, "IC Corporation");
    VALUES.put(0x114E, "Nikon Systems Inc");
    VALUES.put(0x114F, "Digi International");
    VALUES.put(0x1150, "Thinking Machines Corporation");
    VALUES.put(0x1151, "JAE Electronics Inc.");
    VALUES.put(0x1153, "Land Win Electronic Corp");
    VALUES.put(0x1154, "Melco Inc");
    VALUES.put(0x1155, "Pine Technology Ltd");
    VALUES.put(0x1156, "Periscope Engineering");
    VALUES.put(0x1157, "Avsys Corporation");
    VALUES.put(0x1158, "Voarx R&D Inc");
    VALUES.put(0x1159, "Mutech");
    VALUES.put(0x115A, "Harlequin Ltd");
    VALUES.put(0x115B, "Parallax Graphics");
    VALUES.put(0x115C, "Photron Ltd.");
    VALUES.put(0x115D, "Xircom");
    VALUES.put(0x115E, "Peer Protocols Inc");
    VALUES.put(0x115F, "Maxtor Corporation");
    VALUES.put(0x1160, "Megasoft Inc");
    VALUES.put(0x1161, "PFU Ltd");
    VALUES.put(0x1162, "OA Laboratory Co Ltd");
    VALUES.put(0x1163, "mohamed alsherif");
    VALUES.put(0x1164, "Advanced Peripherals Tech");
    VALUES.put(0x1165, "Imagraph Corporation");
    VALUES.put(0x1166, "Broadcom / ServerWorks");
    VALUES.put(0x1167, "Mutoh Industries Inc");
    VALUES.put(0x1168, "Thine Electronics Inc");
    VALUES.put(0x1169, "Centre f/Dev. of Adv. Computing");
    VALUES.put(0x116A, "Luminex Software, Inc");
    VALUES.put(0x116B, "Connectware Inc");
    VALUES.put(0x116C, "Intelligent Resources");
    VALUES.put(0x116E, "Electronics for Imaging");
    VALUES.put(0x1170, "Inventec Corporation");
    VALUES.put(0x1172, "Altera Corporation");
    VALUES.put(0x1173, "Adobe Systems");
    VALUES.put(0x1174, "Bridgeport Machines");
    VALUES.put(0x1175, "Mitron Computer Inc.");
    VALUES.put(0x1176, "SBE");
    VALUES.put(0x1177, "Silicon Engineering");
    VALUES.put(0x1178, "Alfa Inc");
    VALUES.put(0x1179, "Toshiba corporation");
    VALUES.put(0x117A, "A-Trend Technology");
    VALUES.put(0x117B, "LG (Lucky Goldstar) Electronics Inc.");
    VALUES.put(0x117C, "Atto Technology");
    VALUES.put(0x117D, "Becton & Dickinson");
    VALUES.put(0x117E, "T/R Systems");
    VALUES.put(0x117F, "Integrated Circuit Systems");
    VALUES.put(0x1180, "RicohCompany,Ltd.");
    VALUES.put(0x1183, "Fujikura Ltd");
    VALUES.put(0x1184, "Forks Inc");
    VALUES.put(0x1185, "Dataworld");
    VALUES.put(0x1186, "D-Link System Inc");
    VALUES.put(0x1187, "Philips Healthcare");
    VALUES.put(0x1188, "Shima Seiki Manufacturing Ltd.");
    VALUES.put(0x1189, "Matsushita Electronics");
    VALUES.put(0x118A, "Hilevel Technology");
    VALUES.put(0x118B, "Hypertec Pty Ltd");
    VALUES.put(0x118C, "Corollary Inc");
    VALUES.put(0x118D, "BitFlow Inc");
    VALUES.put(0x118E, "Hermstedt AG");
    VALUES.put(0x118F, "Green Logic");
    VALUES.put(0x1190, "Tripace");
    VALUES.put(0x1191, "Acard Technology Corp.");
    VALUES.put(0x1192, "Densan Co. Ltd");
    VALUES.put(0x1194, "Toucan Technology");
    VALUES.put(0x1195, "Ratoc System Inc");
    VALUES.put(0x1196, "Hytec Electronics Ltd");
    VALUES.put(0x1197, "Gage Applied Technologies");
    VALUES.put(0x1198, "Lambda Systems Inc");
    VALUES.put(0x1199, "Attachmate Corp.");
    VALUES.put(0x119A, "Mind/Share Inc.");
    VALUES.put(0x119B, "Omega Micro Inc.");
    VALUES.put(0x119C, "Information Technology Inst.");
    VALUES.put(0x119D, "Bug Sapporo Japan");
    VALUES.put(0x119E, "Fujitsu Microelectronics Ltd.");
    VALUES.put(0x119F, "Bull Hn Information Systems");
    VALUES.put(0x11A1, "Hamamatsu Photonics K.K.");
    VALUES.put(0x11A2, "Sierra Research and Technology");
    VALUES.put(0x11A3, "Deuretzbacher GmbH & Co. Eng. KG");
    VALUES.put(0x11A4, "Barco");
    VALUES.put(0x11A5, "MicroUnity Systems Engineering Inc.");
    VALUES.put(0x11A6, "Pure Data");
    VALUES.put(0x11A7, "Power Computing Corp.");
    VALUES.put(0x11A8, "Systech Corp.");
    VALUES.put(0x11A9, "InnoSys Inc.");
    VALUES.put(0x11AA, "Actel");
    VALUES.put(0x11AB, "Marvell Semiconductor");
    VALUES.put(0x11AC, "Canon Information Systems");
    VALUES.put(0x11AD, "Lite-On Technology Corp.");
    VALUES.put(0x11AE, "Scitex Corporation Ltd");
    VALUES.put(0x11AF, "Avid Technology, Inc.");
    VALUES.put(0x11B0, "Quicklogic Corp");
    VALUES.put(0x11B1, "Apricot Computers");
    VALUES.put(0x11B2, "Eastman Kodak");
    VALUES.put(0x11B3, "Barr Systems Inc.");
    VALUES.put(0x11B4, "Leitch Technology International");
    VALUES.put(0x11B5, "Radstone Technology Ltd.");
    VALUES.put(0x11B6, "United Video Corp");
    VALUES.put(0x11B7, "Motorola");
    VALUES.put(0x11B8, "Xpoint Technologies Inc");
    VALUES.put(0x11B9, "Pathlight Technology Inc.");
    VALUES.put(0x11BA, "Videotron Corp");
    VALUES.put(0x11BB, "Pyramid Technology");
    VALUES.put(0x11BC, "Network Peripherals Inc");
    VALUES.put(0x11BD, "Pinnacle system");
    VALUES.put(0x11BE, "International Microcircuits Inc");
    VALUES.put(0x11BF, "Astrodesign Inc.");
    VALUES.put(0x11C1, "LSI Corporation");
    VALUES.put(0x11C2, "Sand Microelectronics");
    VALUES.put(0x11C4, "Document Technologies Ind.");
    VALUES.put(0x11C5, "Shiva Corporatin");
    VALUES.put(0x11C6, "Dainippon Screen Mfg. Co");
    VALUES.put(0x11C7, "D.C.M. Data Systems");
    VALUES.put(0x11C8, "Dolphin Interconnect Solutions");
    VALUES.put(0x11C9, "MAGMA");
    VALUES.put(0x11CA, "LSI Systems Inc");
    VALUES.put(0x11CB, "Specialix International Ltd.");
    VALUES.put(0x11CC, "Michels & Kleberhoff Computer GmbH");
    VALUES.put(0x11CD, "HAL Computer Systems Inc.");
    VALUES.put(0x11CE, "Primary Rate Inc");
    VALUES.put(0x11CF, "Pioneer Electronic Corporation");
    VALUES.put(0x11D0, "BAE SYSTEMS - Manassas");
    VALUES.put(0x11D1, "AuraVision Corporation");
    VALUES.put(0x11D2, "Intercom Inc.");
    VALUES.put(0x11D3, "Trancell Systems Inc");
    VALUES.put(0x11D4, "Analog Devices, Inc.");
    VALUES.put(0x11D5, "Tahoma Technology");
    VALUES.put(0x11D6, "Tekelec Technologies");
    VALUES.put(0x11D7, "TRENTON Technology, Inc.");
    VALUES.put(0x11D8, "Image Technologies Development");
    VALUES.put(0x11D9, "Tec Corporation");
    VALUES.put(0x11DA, "Novell");
    VALUES.put(0x11DB, "Sega Enterprises Ltd");
    VALUES.put(0x11DC, "Questra Corp");
    VALUES.put(0x11DD, "Crosfield Electronics Ltd");
    VALUES.put(0x11DE, "Zoran Corporation");
    VALUES.put(0x11E1, "Gec Plessey Semi Inc");
    VALUES.put(0x11E2, "Samsung Information Systems America");
    VALUES.put(0x11E3, "Quicklogic Corp");
    VALUES.put(0x11E4, "Second Wave Inc");
    VALUES.put(0x11E5, "IIX Consulting");
    VALUES.put(0x11E6, "Mitsui-Zosen System Research");
    VALUES.put(0x11E8, "Digital Processing Systems Inc");
    VALUES.put(0x11E9, "Highwater Designs Ltd");
    VALUES.put(0x11EA, "Elsag Bailey");
    VALUES.put(0x11EB, "Formation, Inc");
    VALUES.put(0x11EC, "Coreco Inc");
    VALUES.put(0x11ED, "Mediamatics");
    VALUES.put(0x11EE, "Dome Imaging Systems Inc");
    VALUES.put(0x11EF, "Nicolet Technologies BV");
    VALUES.put(0x11F0, "Triya");
    VALUES.put(0x11F2, "Picture Tel Japan KK");
    VALUES.put(0x11F3, "Keithley Instruments, Inc");
    VALUES.put(0x11F4, "Kinetic Systems Corporation");
    VALUES.put(0x11F5, "Computing Devices Intl");
    VALUES.put(0x11F6, "Powermatic Data Systems Ltd");
    VALUES.put(0x11F7, "Scientific Atlanta");
    VALUES.put(0x11F8, "PMC-Sierra Inc.");
    VALUES.put(0x11F9, "I-Cube Inc");
    VALUES.put(0x11FA, "Kasan Electronics Co Ltd");
    VALUES.put(0x11FB, "Datel Inc");
    VALUES.put(0x11FD, "High Street Consultants");
    VALUES.put(0x11FE, "Comtrol Corp");
    VALUES.put(0x11FF, "Scion Corp");
    VALUES.put(0x1200, "CSS Corp");
    VALUES.put(0x1201, "Vista Controls Corp");
    VALUES.put(0x1202, "Network General Corp");
    VALUES.put(0x1203, "Bayer Corporation Agfa Div");
    VALUES.put(0x1204, "Lattice Semiconductor Corp");
    VALUES.put(0x1205, "Array Corp");
    VALUES.put(0x1206, "Amdahl Corp");
    VALUES.put(0x1208, "Parsytec GmbH");
    VALUES.put(0x1209, "Sci Systems Inc");
    VALUES.put(0x120A, "Synaptel");
    VALUES.put(0x120B, "Adaptive Solutions");
    VALUES.put(0x120D, "Compression Labs Inc.");
    VALUES.put(0x120E, "Cyclades Corporation");
    VALUES.put(0x120F, "Essential Communications");
    VALUES.put(0x1210, "Hyperparallel Technologies");
    VALUES.put(0x1211, "Braintech Inc");
    VALUES.put(0x1213, "Applied Intelligent Systems Inc");
    VALUES.put(0x1214, "Performance Technologies Inc");
    VALUES.put(0x1215, "Interware Co Ltd");
    VALUES.put(0x1216, "Purup-Eskofot A/S");
    VALUES.put(0x1217, "O2Micro Inc");
    VALUES.put(0x1218, "Hybricon Corp");
    VALUES.put(0x1219, "First Virtual Corp");
    VALUES.put(0x121A, "3dfx Interactive Inc");
    VALUES.put(0x121B, "Advanced Telecommunications Modules");
    VALUES.put(0x121C, "Nippon Texa Co Ltd");
    VALUES.put(0x121D, "LiPPERT Embedded Computers GmbH");
    VALUES.put(0x121E, "CSPI");
    VALUES.put(0x121F, "Arcus Technology Inc");
    VALUES.put(0x1220, "Ariel Corporation");
    VALUES.put(0x1221, "Contec Microelectronics Europe BV");
    VALUES.put(0x1222, "Ancor Communications Inc");
    VALUES.put(0x1223, "Artesyn Embedded Technologies");
    VALUES.put(0x1224, "Interactive Images");
    VALUES.put(0x1225, "Power I/O Inc.");
    VALUES.put(0x1227, "Tech-Source");
    VALUES.put(0x1228, "Norsk Elektro Optikk A/S");
    VALUES.put(0x1229, "Data Kinesis Inc.");
    VALUES.put(0x122A, "Integrated Telecom");
    VALUES.put(0x122B, "LG Industrial Systems Co. Ltd.");
    VALUES.put(0x122C, "sci-worx GmbH");
    VALUES.put(0x122D, "Aztech System Ltd");
    VALUES.put(0x122E, "Absolute Analysis");
    VALUES.put(0x122F, "Andrew Corp.");
    VALUES.put(0x1230, "Fishcamp Engineering");
    VALUES.put(0x1231, "Woodward McCoach Inc.");
    VALUES.put(0x1233, "Bus-Tech Inc.");
    VALUES.put(0x1234, "Technical Corp");
    VALUES.put(0x1236, "Sigma Designs, Inc");
    VALUES.put(0x1237, "Alta Technology Corp.");
    VALUES.put(0x1238, "Adtran");
    VALUES.put(0x1239, "The 3DO Company");
    VALUES.put(0x123A, "Visicom Laboratories Inc.");
    VALUES.put(0x123B, "Seeq Technology Inc.");
    VALUES.put(0x123C, "Century Systems Inc.");
    VALUES.put(0x123D, "Engineering Design Team Inc.");
    VALUES.put(0x123F, "C-Cube Microsystems");
    VALUES.put(0x1240, "Marathon Technologies Corp.");
    VALUES.put(0x1241, "DSC Communications");
    VALUES.put(0x1242, "JNI Corporation");
    VALUES.put(0x1243, "Delphax");
    VALUES.put(0x1244, "AVM AUDIOVISUELLES MKTG & Computer GmbH");
    VALUES.put(0x1245, "APD S.A.");
    VALUES.put(0x1246, "Dipix Technologies Inc");
    VALUES.put(0x1247, "Xylon Research Inc.");
    VALUES.put(0x1248, "Central Data Corp.");
    VALUES.put(0x1249, "Samsung Electronics Co. Ltd.");
    VALUES.put(0x124A, "AEG Electrocom GmbH");
    VALUES.put(0x124C, "Solitron Technologies Inc.");
    VALUES.put(0x124D, "Stallion Technologies");
    VALUES.put(0x124E, "Cylink");
    VALUES.put(0x124F, "Infortrend Technology Inc");
    VALUES.put(0x1250, "Hitachi Microcomputer System Ltd.");
    VALUES.put(0x1251, "VLSI Solution OY");
    VALUES.put(0x1253, "Guzik Technical Enterprises");
    VALUES.put(0x1254, "Linear Systems Ltd.");
    VALUES.put(0x1255, "Optibase Ltd.");
    VALUES.put(0x1256, "Perceptive Solutions Inc.");
    VALUES.put(0x1257, "Vertex Networks Inc.");
    VALUES.put(0x1258, "Gilbarco Inc.");
    VALUES.put(0x1259, "Allied Telesyn International");
    VALUES.put(0x125A, "ABB Power Systems");
    VALUES.put(0x125B, "Asix Electronics Corp.");
    VALUES.put(0x125C, "Aurora Technologies Inc.");
    VALUES.put(0x125D, "ESS Technology");
    VALUES.put(0x125E, "Specialvideo Engineering SRL");
    VALUES.put(0x125F, "Concurrent Technologies Inc.");
    VALUES.put(0x1260, "Intersil Corporation");
    VALUES.put(0x1261, "Matsushita-Kotobuki Electronics Indu");
    VALUES.put(0x1262, "ES Computer Co. Ltd.");
    VALUES.put(0x1263, "Sonic Solutions");
    VALUES.put(0x1264, "Aval Nagasaki Corp.");
    VALUES.put(0x1265, "Casio Computer Co. Ltd.");
    VALUES.put(0x1266, "Microdyne Corp.");
    VALUES.put(0x1267, "S.A. Telecommunications");
    VALUES.put(0x1268, "Tektronix");
    VALUES.put(0x1269, "Thomson-CSF/TTM");
    VALUES.put(0x126A, "Lexmark International Inc.");
    VALUES.put(0x126B, "Adax Inc.");
    VALUES.put(0x126C, "Nortel Networks Corp.");
    VALUES.put(0x126D, "Splash Technology Inc.");
    VALUES.put(0x126E, "Sumitomo Metal Industries Ltd.");
    VALUES.put(0x126F, "Silicon Motion");
    VALUES.put(0x1270, "Olympus Optical Co. Ltd.");
    VALUES.put(0x1271, "GW Instruments");
    VALUES.put(0x1272, "themrtaish");
    VALUES.put(0x1273, "Hughes Network Systems");
    VALUES.put(0x1274, "Ensoniq");
    VALUES.put(0x1275, "Network Appliance");
    VALUES.put(0x1276, "Switched Network Technologies Inc.");
    VALUES.put(0x1277, "Comstream");
    VALUES.put(0x1278, "Transtech Parallel Systems");
    VALUES.put(0x1279, "Transmeta Corp.");
    VALUES.put(0x127B, "Pixera Corp");
    VALUES.put(0x127C, "Crosspoint Solutions Inc.");
    VALUES.put(0x127D, "Vela Research LP");
    VALUES.put(0x127E, "Winnov L.P.");
    VALUES.put(0x127F, "Fujifilm");
    VALUES.put(0x1280, "Photoscript Group Ltd.");
    VALUES.put(0x1281, "Yokogawa Electronic Corp.");
    VALUES.put(0x1282, "Davicom Semiconductor Inc.");
    VALUES.put(0x1283, "Waldo");
    VALUES.put(0x1285, "Platform Technologies Inc.");
    VALUES.put(0x1286, "MAZeT GmbH");
    VALUES.put(0x1287, "LuxSonor Inc.");
    VALUES.put(0x1288, "Timestep Corp.");
    VALUES.put(0x1289, "AVC Technology Inc.");
    VALUES.put(0x128A, "Asante Technologies Inc.");
    VALUES.put(0x128B, "Transwitch Corp.");
    VALUES.put(0x128C, "Retix Corp.");
    VALUES.put(0x128D, "G2 Networks Inc.");
    VALUES.put(0x128F, "Tateno Dennou Inc.");
    VALUES.put(0x1290, "Sord Computer Corp.");
    VALUES.put(0x1291, "NCS Computer Italia");
    VALUES.put(0x1292, "Tritech Microelectronics Intl PTE");
    VALUES.put(0x1293, "Media Reality Technology");
    VALUES.put(0x1294, "Rhetorex Inc.");
    VALUES.put(0x1295, "Imagenation Corp.");
    VALUES.put(0x1296, "Kofax Image Products");
    VALUES.put(0x1297, "Shuttle Computer");
    VALUES.put(0x1298, "Spellcaster Telecommunications Inc.");
    VALUES.put(0x1299, "Knowledge Technology Laboratories");
    VALUES.put(0x129A, "Curtiss Wright Controls Electronic Systems");
    VALUES.put(0x129B, "Image Access");
    VALUES.put(0x129D, "CompCore Multimedia Inc.");
    VALUES.put(0x129E, "Victor Co. of Japan Ltd.");
    VALUES.put(0x129F, "OEC Medical Systems Inc.");
    VALUES.put(0x12A0, "Allen Bradley Co.");
    VALUES.put(0x12A1, "Simpact Inc");
    VALUES.put(0x12A2, "NewGen Systems Corp.");
    VALUES.put(0x12A3, "Lucent Technologies AMR");
    VALUES.put(0x12A4, "NTT Electronics Corp.");
    VALUES.put(0x12A5, "Vision Dynamics Ltd.");
    VALUES.put(0x12A6, "Scalable Networks Inc.");
    VALUES.put(0x12A7, "AMO GmbH");
    VALUES.put(0x12A8, "News Datacom");
    VALUES.put(0x12A9, "Xiotech Corp.");
    VALUES.put(0x12AA, "SDL Communications Inc.");
    VALUES.put(0x12AB, "Yuan Yuan Enterprise Co. Ltd.");
    VALUES.put(0x12AC, "MeasureX Corp.");
    VALUES.put(0x12AD, "MULTIDATA GmbH");
    VALUES.put(0x12AE, "Alteon Networks Inc.");
    VALUES.put(0x12AF, "TDK USA Corp.");
    VALUES.put(0x12B0, "Jorge Scientific Corp.");
    VALUES.put(0x12B1, "GammaLink");
    VALUES.put(0x12B2, "General Signal Networks");
    VALUES.put(0x12B3, "Interface Corp. Ltd.");
    VALUES.put(0x12B4, "Future Tel Inc.");
    VALUES.put(0x12B5, "Granite Systems Inc.");
    VALUES.put(0x12B7, "Acumen");
    VALUES.put(0x12B8, "Korg");
    VALUES.put(0x12B9, "3Com Corporation");
    VALUES.put(0x12BA, "Bittware, Inc");
    VALUES.put(0x12BB, "Nippon Unisoft Corp.");
    VALUES.put(0x12BC, "Array Microsystems");
    VALUES.put(0x12BD, "Computerm Corp.");
    VALUES.put(0x12BF, "Fujifilm Microdevices");
    VALUES.put(0x12C0, "Infimed");
    VALUES.put(0x12C1, "GMM Research Corp.");
    VALUES.put(0x12C2, "Mentec Ltd.");
    VALUES.put(0x12C3, "Holtek Microelectronics Inc.");
    VALUES.put(0x12C4, "Connect Tech Inc.");
    VALUES.put(0x12C5, "Picture Elements Inc.");
    VALUES.put(0x12C6, "Mitani Corp.");
    VALUES.put(0x12C7, "Dialogic Corp.");
    VALUES.put(0x12C8, "G Force Co. Ltd.");
    VALUES.put(0x12C9, "Gigi Operations");
    VALUES.put(0x12CA, "Integrated Computing Engines, Inc.");
    VALUES.put(0x12CB, "Antex Electronics Corp.");
    VALUES.put(0x12CC, "Pluto Technologies International");
    VALUES.put(0x12CD, "Aims Lab");
    VALUES.put(0x12CE, "Netspeed Inc.");
    VALUES.put(0x12CF, "Prophet Systems Inc.");
    VALUES.put(0x12D0, "GDE Systems Inc.");
    VALUES.put(0x12D1, "Huawei Technologies Co., Ltd.");
    VALUES.put(0x12D3, "Vingmed Sound A/S");
    VALUES.put(0x12D4, "Ulticom, Inc.");
    VALUES.put(0x12D5, "Equator Technologies");
    VALUES.put(0x12D6, "Analogic Corp.");
    VALUES.put(0x12D7, "Biotronic SRL");
    VALUES.put(0x12D8, "Pericom Semiconductor");
    VALUES.put(0x12D9, "Aculab Plc.");
    VALUES.put(0x12DA, "TrueTime");
    VALUES.put(0x12DB, "Annapolis Micro Systems Inc.");
    VALUES.put(0x12DC, "Symicron Computer Communication Ltd.");
    VALUES.put(0x12DD, "Management Graphics Inc.");
    VALUES.put(0x12DE, "Rainbow Technologies");
    VALUES.put(0x12DF, "SBS Technologies Inc.");
    VALUES.put(0x12E0, "Chase Research PLC");
    VALUES.put(0x12E1, "Nintendo Co. Ltd.");
    VALUES.put(0x12E2, "Datum Inc. Bancomm-Timing Division");
    VALUES.put(0x12E3, "Imation Corp. - Medical Imaging Syst");
    VALUES.put(0x12E4, "Brooktrout Technology Inc.");
    VALUES.put(0x12E6, "Cirel Systems");
    VALUES.put(0x12E7, "Sebring Systems Inc");
    VALUES.put(0x12E8, "CRISC Corp.");
    VALUES.put(0x12E9, "GE Spacenet");
    VALUES.put(0x12EB, "Aureal Semiconductor");
    VALUES.put(0x12EC, "3A International Inc.");
    VALUES.put(0x12ED, "Optivision Inc.");
    VALUES.put(0x12EE, "Orange Micro, Inc.");
    VALUES.put(0x12EF, "Vienna Systems");
    VALUES.put(0x12F0, "Pentek");
    VALUES.put(0x12F1, "Sorenson Vision Inc.");
    VALUES.put(0x12F2, "Gammagraphx Inc.");
    VALUES.put(0x12F4, "Megatel");
    VALUES.put(0x12F5, "Forks");
    VALUES.put(0x12F7, "Cognex");
    VALUES.put(0x12F8, "Electronic-Design GmbH");
    VALUES.put(0x12F9, "FourFold Technologies");
    VALUES.put(0x12FB, "Spectrum Signal Processing");
    VALUES.put(0x12FC, "Capital Equipment Corp");
    VALUES.put(0x12FE, "esd Electronic System Design GmbH");
    VALUES.put(0x1303, "Innovative Integration");
    VALUES.put(0x1304, "Juniper Networks Inc.");
    VALUES.put(0x1307, "ComputerBoards");
    VALUES.put(0x1308, "Jato Technologies Inc.");
    VALUES.put(0x130A, "Mitsubishi Electric Microcomputer");
    VALUES.put(0x130B, "Colorgraphic Communications Corp");
    VALUES.put(0x130F, "Advanet Inc.");
    VALUES.put(0x1310, "Gespac");
    VALUES.put(0x1312, "Microscan Systems Inc");
    VALUES.put(0x1313, "Yaskawa Electric Co.");
    VALUES.put(0x1316, "Teradyne Inc.");
    VALUES.put(0x1317, "ADMtek Inc");
    VALUES.put(0x1318, "Packet Engines, Inc.");
    VALUES.put(0x1319, "Forte Media");
    VALUES.put(0x131F, "SIIG");
    VALUES.put(0x1325, "austriamicrosystems");
    VALUES.put(0x1326, "Seachange International");
    VALUES.put(0x1328, "CIFELLI SYSTEMS CORPORATION");
    VALUES.put(0x1331, "RadiSys Corporation");
    VALUES.put(0x1332, "Curtiss-Wright Controls Embedded Computing");
    VALUES.put(0x1335, "Videomail Inc.");
    VALUES.put(0x133D, "Prisa Networks");
    VALUES.put(0x133F, "SCM Microsystems");
    VALUES.put(0x1342, "Promax Systems Inc");
    VALUES.put(0x1344, "Micron Technology, Inc.");
    VALUES.put(0x1347, "Spectracom Corporation");
    VALUES.put(0x134A, "DTC Technology Corp.");
    VALUES.put(0x134B, "ARK Research Corp.");
    VALUES.put(0x134C, "Chori Joho System Co. Ltd");
    VALUES.put(0x134D, "PCTEL Inc.");
    VALUES.put(0x135A, "Brain Boxes Limited");
    VALUES.put(0x135B, "Giganet Inc.");
    VALUES.put(0x135C, "Quatech Inc");
    VALUES.put(0x135D, "ABB Network Partner AB");
    VALUES.put(0x135E, "Sealevel Systems Inc.");
    VALUES.put(0x135F, "I-Data International A-S");
    VALUES.put(0x1360, "Meinberg Funkuhren GmbH & Co. KG");
    VALUES.put(0x1361, "Soliton Systems K.K.");
    VALUES.put(0x1363, "Phoenix Technologies Ltd");
    VALUES.put(0x1365, "Hypercope Corp.");
    VALUES.put(0x1366, "Teijin Seiki Co. Ltd.");
    VALUES.put(0x1367, "Hitachi Zosen Corporation");
    VALUES.put(0x1368, "Skyware Corporation");
    VALUES.put(0x1369, "Digigram");
    VALUES.put(0x136B, "Kawasaki Steel Corporation");
    VALUES.put(0x136C, "Adtek System Science Co Ltd");
    VALUES.put(0x1375, "Boeing - Sunnyvale");
    VALUES.put(0x137A, "Mark Of The Unicorn Inc");
    VALUES.put(0x137B, "PPT Vision");
    VALUES.put(0x137C, "Iwatsu Electric Co Ltd");
    VALUES.put(0x137D, "Dynachip Corporation");
    VALUES.put(0x137E, "Patriot Scientific Corp.");
    VALUES.put(0x1380, "Sanritz Automation Co LTC");
    VALUES.put(0x1381, "Brains Co. Ltd");
    VALUES.put(0x1382, "Marian - Electronic & Software");
    VALUES.put(0x1384, "Stellar Semiconductor Inc");
    VALUES.put(0x1385, "Netgear");
    VALUES.put(0x1387, "Curtiss-Wright Controls Electronic Systems");
    VALUES.put(0x1388, "Hitachi Information Technology Co Ltd");
    VALUES.put(0x1389, "Applicom International");
    VALUES.put(0x138A, "Validity Sensors, Inc.");
    VALUES.put(0x138B, "Tokimec Inc");
    VALUES.put(0x138E, "Basler GMBH");
    VALUES.put(0x138F, "Patapsco Designs Inc");
    VALUES.put(0x1390, "Concept Development Inc.");
    VALUES.put(0x1393, "Moxa Technologies Co Ltd");
    VALUES.put(0x1394, "Level One Communications");
    VALUES.put(0x1395, "Ambicom Inc");
    VALUES.put(0x1396, "Cipher Systems Inc");
    VALUES.put(0x1397, "Cologne Chip Designs GmbH");
    VALUES.put(0x1398, "Clarion Co. Ltd");
    VALUES.put(0x139A, "Alacritech Inc");
    VALUES.put(0x139D, "Xstreams PLC/ EPL Limited");
    VALUES.put(0x139E, "Echostar Data Networks");
    VALUES.put(0x13A0, "Crystal Group Inc");
    VALUES.put(0x13A1, "Kawasaki Heavy Industries Ltd");
    VALUES.put(0x13A3, "HI-FN Inc.");
    VALUES.put(0x13A4, "Rascom Inc");
    VALUES.put(0x13A7, "amc330");
    VALUES.put(0x13A8, "Exar Corp.");
    VALUES.put(0x13A9, "Siemens Healthcare");
    VALUES.put(0x13AA, "Nortel Networks - BWA Division");
    VALUES.put(0x13AF, "T.Sqware");
    VALUES.put(0x13B1, "Tamura Corporation");
    VALUES.put(0x13B4, "Wellbean Co Inc");
    VALUES.put(0x13B5, "ARM Ltd");
    VALUES.put(0x13B6, "DLoG Gesellschaft fÃ¼r elektronische Datentechnik mbH");
    VALUES.put(0x13B8, "Nokia Telecommunications OY");
    VALUES.put(0x13BD, "Sharp Corporation");
    VALUES.put(0x13BF, "Sharewave Inc");
    VALUES.put(0x13C0, "Microgate Corp.");
    VALUES.put(0x13C1, "LSI");
    VALUES.put(0x13C2, "Technotrend Systemtechnik GMBH");
    VALUES.put(0x13C3, "Janz Computer AG");
    VALUES.put(0x13C7, "Blue Chip Technology Ltd");
    VALUES.put(0x13CC, "Metheus Corporation");
    VALUES.put(0x13CF, "Studio Audio & Video Ltd");
    VALUES.put(0x13D0, "B2C2 Inc");
    VALUES.put(0x13D1, "AboCom Systems, Inc");
    VALUES.put(0x13D4, "Graphics Microsystems Inc");
    VALUES.put(0x13D6, "K.I. Technology Co Ltd");
    VALUES.put(0x13D7, "Toshiba Engineering Corporation");
    VALUES.put(0x13D8, "Phobos Corporation");
    VALUES.put(0x13D9, "Apex Inc");
    VALUES.put(0x13DC, "Netboost Corporation");
    VALUES.put(0x13DE, "ABB Robotics Products AB");
    VALUES.put(0x13DF, "E-Tech Inc.");
    VALUES.put(0x13E0, "GVC Corporation");
    VALUES.put(0x13E3, "Nest Inc");
    VALUES.put(0x13E4, "Calculex Inc");
    VALUES.put(0x13E5, "Telesoft Design Ltd");
    VALUES.put(0x13E9, "Intraserver Technology Inc");
    VALUES.put(0x13EA, "Dallas Semiconductor");
    VALUES.put(0x13F0, "IC Plus Corporation");
    VALUES.put(0x13F1, "OCE - Industries S.A.");
    VALUES.put(0x13F4, "Troika Networks Inc");
    VALUES.put(0x13F6, "C-Media Electronics Inc.");
    VALUES.put(0x13F9, "NTT Advanced Technology Corp.");
    VALUES.put(0x13FA, "Pentland Systems Ltd.");
    VALUES.put(0x13FB, "Aydin Corp");
    VALUES.put(0x13FD, "Micro Science Inc");
    VALUES.put(0x13FE, "Advantech Co., Ltd.");
    VALUES.put(0x13FF, "Silicon Spice Inc.");
    VALUES.put(0x1400, "ArtX Inc");
    VALUES.put(0x1402, "Meilhaus Electronic GmbH Germany");
    VALUES.put(0x1404, "Fundamental Software Inc");
    VALUES.put(0x1406, "Oce Print Logics Technologies S.A.");
    VALUES.put(0x1407, "Lava Computer MFG Inc.");
    VALUES.put(0x1408, "Aloka Co. Ltd");
    VALUES.put(0x1409, "SUNIX Co., Ltd.");
    VALUES.put(0x140A, "DSP Research Inc");
    VALUES.put(0x140B, "Ramix Inc");
    VALUES.put(0x140D, "Matsushita Electric Works Ltd");
    VALUES.put(0x140F, "Salient Systems Corp");
    VALUES.put(0x1412, "IC Ensemble, Inc.");
    VALUES.put(0x1413, "Addonics");
    VALUES.put(0x1415, "Oxford Semiconductor Ltd - now part of PLX Technology");
    VALUES.put(0x1418, "Kyushu Electronics Systems Inc");
    VALUES.put(0x1419, "Excel Switching Corp");
    VALUES.put(0x141B, "Zoom Telephonics Inc");
    VALUES.put(0x141E, "Fanuc Co. Ltd");
    VALUES.put(0x141F, "Visiontech Ltd");
    VALUES.put(0x1420, "Psion Dacom PLC");
    VALUES.put(0x1425, "Chelsio Communications");
    VALUES.put(0x1428, "Edec Co Ltd");
    VALUES.put(0x1429, "Unex Technology Corp.");
    VALUES.put(0x142A, "Kingmax Technology Inc");
    VALUES.put(0x142B, "Radiolan");
    VALUES.put(0x142C, "Minton Optic Industry Co Ltd");
    VALUES.put(0x142D, "Pixstream Inc");
    VALUES.put(0x1430, "ITT Aerospace/Communications Division");
    VALUES.put(0x1433, "Eltec Elektronik AG");
    VALUES.put(0x1435, "RTD Embedded Technologies, Inc.");
    VALUES.put(0x1436, "CIS Technology Inc");
    VALUES.put(0x1437, "Nissin Inc Co");
    VALUES.put(0x1438, "Atmel-Dream");
    VALUES.put(0x143F, "Lightwell Co Ltd - Zax Division");
    VALUES.put(0x1441, "Agie SA.");
    VALUES.put(0x1443, "Unibrain S.A.");
    VALUES.put(0x1445, "Logical Co Ltd");
    VALUES.put(0x1446, "Graphin Co., LTD");
    VALUES.put(0x1447, "Aim GMBH");
    VALUES.put(0x1448, "Alesis Studio");
    VALUES.put(0x144A, "ADLINK Technology Inc");
    VALUES.put(0x144B, "Loronix Information Systems, Inc.");
    VALUES.put(0x144D, "sanyo");
    VALUES.put(0x1450, "Octave Communications Ind.");
    VALUES.put(0x1451, "SP3D Chip Design GMBH");
    VALUES.put(0x1453, "Mycom Inc");
    VALUES.put(0x1458, "Giga-Byte Technologies");
    VALUES.put(0x145C, "Cryptek");
    VALUES.put(0x145F, "Baldor Electric Company");
    VALUES.put(0x1460, "Dynarc Inc");
    VALUES.put(0x1462, "Micro-Star International Co Ltd");
    VALUES.put(0x1463, "Fast Corporation");
    VALUES.put(0x1464, "Interactive Circuits & Systems Ltd");
    VALUES.put(0x1468, "Ambit Microsystems Corp.");
    VALUES.put(0x1469, "Cleveland Motion Controls");
    VALUES.put(0x146C, "Ruby Tech Corp.");
    VALUES.put(0x146D, "Tachyon Inc.");
    VALUES.put(0x146E, "WMS Gaming");
    VALUES.put(0x1471, "Integrated Telecom Express Inc");
    VALUES.put(0x1473, "Zapex Technologies Inc");
    VALUES.put(0x1474, "Doug Carson & Associates");
    VALUES.put(0x1477, "Net Insight");
    VALUES.put(0x1478, "Diatrend Corporation");
    VALUES.put(0x147B, "Abit Computer Corp.");
    VALUES.put(0x147F, "Nihon Unisys Ltd.");
    VALUES.put(0x1482, "Isytec - Integrierte Systemtechnik Gmbh");
    VALUES.put(0x1483, "Labway Coporation");
    VALUES.put(0x1485, "Erma - Electronic GMBH");
    VALUES.put(0x1489, "KYE Systems Corporation");
    VALUES.put(0x148A, "Opto 22");
    VALUES.put(0x148B, "Innomedialogic Inc.");
    VALUES.put(0x148C, "C.P. Technology Co. Ltd");
    VALUES.put(0x148D, "Digicom Systems Inc.");
    VALUES.put(0x148E, "OSI Plus Corporation");
    VALUES.put(0x148F, "Plant Equipment Inc.");
    VALUES.put(0x1490, "TC Labs Pty Ltd.");
    VALUES.put(0x1491, "Futronic");
    VALUES.put(0x1493, "Maker Communications");
    VALUES.put(0x1495, "Tokai Communications Industry Co. Ltd");
    VALUES.put(0x1496, "Joytech Computer Co. Ltd.");
    VALUES.put(0x1497, "SMA Technologie AG");
    VALUES.put(0x1498, "Tews Technologies");
    VALUES.put(0x1499, "Micro-Technology Co Ltd");
    VALUES.put(0x149A, "Andor Technology Ltd");
    VALUES.put(0x149B, "Seiko Instruments Inc");
    VALUES.put(0x149E, "Mapletree Networks Inc.");
    VALUES.put(0x149F, "Lectron Co Ltd");
    VALUES.put(0x14A0, "Softing AG");
    VALUES.put(0x14A2, "Millennium Engineering Inc");
    VALUES.put(0x14A4, "GVC/BCM Advanced Research");
    VALUES.put(0x14A9, "Hivertec Inc.");
    VALUES.put(0x14AB, "Mentor Graphics Corp.");
    VALUES.put(0x14B1, "Nextcom K.K.");
    VALUES.put(0x14B3, "Xpeed Inc.");
    VALUES.put(0x14B4, "Philips Business Electronics B.V.");
    VALUES.put(0x14B5, "Creamware GmbH");
    VALUES.put(0x14B6, "Quantum Data Corp.");
    VALUES.put(0x14B7, "Proxim Inc.");
    VALUES.put(0x14B9, "Aironet Wireless Communication");
    VALUES.put(0x14BA, "Internix Inc.");
    VALUES.put(0x14BB, "Semtech Corporation");
    VALUES.put(0x14BE, "L3 Communications");
    VALUES.put(0x14C0, "Compal Electronics, Inc.");
    VALUES.put(0x14C1, "Myricom Inc.");
    VALUES.put(0x14C2, "DTK Computer");
    VALUES.put(0x14C4, "Iwasaki Information Systems Co Ltd");
    VALUES.put(0x14C5, "ABB AB (Sweden)");
    VALUES.put(0x14C6, "Data Race Inc");
    VALUES.put(0x14C7, "Modular Technology Ltd.");
    VALUES.put(0x14C8, "Turbocomm Tech Inc");
    VALUES.put(0x14C9, "Odin Telesystems Inc");
    VALUES.put(0x14CB, "Billionton Systems Inc./Cadmus Micro Inc");
    VALUES.put(0x14CD, "Universal Scientific Ind.");
    VALUES.put(0x14CF, "TEK Microsystems Inc.");
    VALUES.put(0x14D4, "Panacom Technology Corporation");
    VALUES.put(0x14D5, "Nitsuko Corporation");
    VALUES.put(0x14D6, "Accusys Inc");
    VALUES.put(0x14D7, "Hirakawa Hewtech Corp");
    VALUES.put(0x14D8, "Hopf Elektronik GMBH");
    VALUES.put(0x14D9, "Alpha Processor Inc");
    VALUES.put(0x14DB, "Avlab Technology Inc.");
    VALUES.put(0x14DC, "Amplicon Liveline Limited");
    VALUES.put(0x14DD, "Imodl Inc.");
    VALUES.put(0x14DE, "Applied Integration Corporation");
    VALUES.put(0x14E3, "Amtelco");
    VALUES.put(0x14E4, "Broadcom");
    VALUES.put(0x14EA, "Planex Communications, Inc.");
    VALUES.put(0x14EB, "Seiko Epson Corporation");
    VALUES.put(0x14EC, "Acqiris");
    VALUES.put(0x14ED, "Datakinetics Ltd");
    VALUES.put(0x14EF, "Carry Computer Eng. Co Ltd");
    VALUES.put(0x14F1, "Conexant");
    VALUES.put(0x14F2, "Mobility Electronics, Inc.");
    VALUES.put(0x14F4, "Tokyo Electronic Industry Co. Ltd.");
    VALUES.put(0x14F5, "Sopac Ltd");
    VALUES.put(0x14F6, "Coyote Technologies LLC");
    VALUES.put(0x14F7, "Wolf Technology Inc");
    VALUES.put(0x14F8, "Audiocodes Inc");
    VALUES.put(0x14F9, "AG Communications");
    VALUES.put(0x14FB, "Transas Marine (UK) Ltd");
    VALUES.put(0x14FC, "Quadrics Ltd");
    VALUES.put(0x14FD, "Silex Technology Inc.");
    VALUES.put(0x14FE, "Archtek Telecom Corp.");
    VALUES.put(0x14FF, "Twinhead International Corp.");
    VALUES.put(0x1501, "Banksoft Canada Ltd");
    VALUES.put(0x1502, "Mitsubishi Electric Logistics Support Co");
    VALUES.put(0x1503, "Kawasaki LSI USA Inc");
    VALUES.put(0x1504, "Kaiser Electronics");
    VALUES.put(0x1506, "Chameleon Systems Inc");
    VALUES.put(0x1507, "Htec Ltd.");
    VALUES.put(0x1509, "First International Computer Inc");
    VALUES.put(0x150B, "Yamashita Systems Corp");
    VALUES.put(0x150C, "Kyopal Co Ltd");
    VALUES.put(0x150D, "Warpspped Inc");
    VALUES.put(0x150E, "C-Port Corporation");
    VALUES.put(0x150F, "Intec GMBH");
    VALUES.put(0x1510, "Behavior Tech Computer Corp");
    VALUES.put(0x1511, "Centillium Technology Corp");
    VALUES.put(0x1512, "Rosun Technologies Inc");
    VALUES.put(0x1513, "Raychem");
    VALUES.put(0x1514, "TFL LAN Inc");
    VALUES.put(0x1515, "ICS Advent");
    VALUES.put(0x1516, "Myson Technology Inc");
    VALUES.put(0x1517, "Echotek Corporation");
    VALUES.put(0x1518, "Kontron Modular Computers GmbH (PEP Modular Computers GMBH)");
    VALUES.put(0x1519, "Telefon Aktiebolaget LM Ericsson");
    VALUES.put(0x151A, "Globetek Inc.");
    VALUES.put(0x151B, "Combox Ltd");
    VALUES.put(0x151C, "Digital Audio Labs Inc");
    VALUES.put(0x151D, "Fujitsu Computer Products Of America");
    VALUES.put(0x151E, "Matrix Corp.");
    VALUES.put(0x151F, "Topic Semiconductor Corp");
    VALUES.put(0x1520, "Chaplet System Inc");
    VALUES.put(0x1521, "Bell Corporation");
    VALUES.put(0x1522, "Mainpine Limited");
    VALUES.put(0x1523, "Music Semiconductors");
    VALUES.put(0x1524, "ENE Technology Inc");
    VALUES.put(0x1525, "Impact Technologies");
    VALUES.put(0x1526, "ISS Inc");
    VALUES.put(0x1527, "Solectron");
    VALUES.put(0x1528, "Acksys");
    VALUES.put(0x1529, "American Microsystems Inc");
    VALUES.put(0x152A, "Quickturn Design Systems");
    VALUES.put(0x152B, "Flytech Technology Co Ltd");
    VALUES.put(0x152C, "Macraigor Systems LLC");
    VALUES.put(0x152D, "Quanta Computer Inc");
    VALUES.put(0x152E, "Melec Inc");
    VALUES.put(0x152F, "Philips - Crypto");
    VALUES.put(0x1532, "Echelon Corporation");
    VALUES.put(0x1533, "Baltimore");
    VALUES.put(0x1534, "Road Corporation");
    VALUES.put(0x1535, "Evergreen Technologies Inc");
    VALUES.put(0x1537, "Datalex Communcations");
    VALUES.put(0x1538, "Aralion Inc.");
    VALUES.put(0x1539, "Atelier Informatiques et Electronique Et");
    VALUES.put(0x153A, "ONO Sokki");
    VALUES.put(0x153B, "Terratec Electronic GMBH");
    VALUES.put(0x153C, "Antal Electronic");
    VALUES.put(0x153D, "Filanet Corporation");
    VALUES.put(0x153E, "Techwell Inc");
    VALUES.put(0x153F, "MIPS Technologies, Inc");
    VALUES.put(0x1540, "Provideo Multimedia Co Ltd");
    VALUES.put(0x1541, "Telocity Inc.");
    VALUES.put(0x1542, "Vivid Technology Inc");
    VALUES.put(0x1543, "Silicon Laboratories");
    VALUES.put(0x1544, "DCM Technologies Ltd.");
    VALUES.put(0x1545, "VisionTek");
    VALUES.put(0x1546, "IOI Technology Corp.");
    VALUES.put(0x1547, "Mitutoyo Corporation");
    VALUES.put(0x1548, "Jet Propulsion Laboratory");
    VALUES.put(0x1549, "Interconnect Systems Solutions");
    VALUES.put(0x154A, "Max Technologies Inc.");
    VALUES.put(0x154B, "Computex Co Ltd");
    VALUES.put(0x154C, "Visual Technology Inc.");
    VALUES.put(0x154D, "PAN International Industrial Corp");
    VALUES.put(0x154E, "Servotest Ltd");
    VALUES.put(0x154F, "Stratabeam Technology");
    VALUES.put(0x1550, "Open Network Co Ltd");
    VALUES.put(0x1551, "Smart Electronic Development GMBH");
    VALUES.put(0x1553, "Chicony Electronics Co Ltd");
    VALUES.put(0x1554, "Prolink Microsystems Corp.");
    VALUES.put(0x1555, "Gesytec GmbH");
    VALUES.put(0x1556, "PLDA");
    VALUES.put(0x1557, "Mediastar Co. Ltd");
    VALUES.put(0x1558, "Clevo/Kapok Computer");
    VALUES.put(0x1559, "SI Logic Ltd");
    VALUES.put(0x155A, "Innomedia Inc");
    VALUES.put(0x155B, "Protac International Corp");
    VALUES.put(0x155C, "s");
    VALUES.put(0x155D, "MAC System Co Ltd");
    VALUES.put(0x155E, "KUKA Roboter GmbH");
    VALUES.put(0x155F, "Perle Systems Limited");
    VALUES.put(0x1560, "Terayon Communications Systems");
    VALUES.put(0x1561, "Viewgraphics Inc");
    VALUES.put(0x1562, "Symbol Technologies, Inc.");
    VALUES.put(0x1563, "A-Trend Technology Co Ltd");
    VALUES.put(0x1564, "Yamakatsu Electronics Industry Co Ltd");
    VALUES.put(0x1565, "Biostar Microtech Intl Corp");
    VALUES.put(0x1566, "Ardent Technologies Inc");
    VALUES.put(0x1567, "Jungsoft");
    VALUES.put(0x1568, "DDK Electronics Inc");
    VALUES.put(0x1569, "Palit Microsystems Inc");
    VALUES.put(0x156A, "Avtec Systems Inc");
    VALUES.put(0x156B, "S2io Inc");
    VALUES.put(0x156C, "Vidac Electronics GMBH");
    VALUES.put(0x156D, "Alpha-Top Corp");
    VALUES.put(0x156E, "Alfa Inc.");
    VALUES.put(0x156F, "M-Systems Flash Disk Pioneers Ltd");
    VALUES.put(0x1570, "Lecroy Corporation");
    VALUES.put(0x1571, "Contemporary Controls");
    VALUES.put(0x1572, "Otis Elevator Company");
    VALUES.put(0x1573, "Lattice - Vantis");
    VALUES.put(0x1574, "Fairchild Semiconductor");
    VALUES.put(0x1575, "Voltaire Advanced Data Security Ltd");
    VALUES.put(0x1576, "Viewcast Com");
    VALUES.put(0x1578, "Hitt");
    VALUES.put(0x1579, "Dual Technology Corporation");
    VALUES.put(0x157A, "Japan Elecronics Ind. Inc");
    VALUES.put(0x157B, "Star Multimedia Corp.");
    VALUES.put(0x157C, "Eurosoft (UK)");
    VALUES.put(0x157D, "Gemflex Networks");
    VALUES.put(0x157E, "Transition Networks");
    VALUES.put(0x157F, "PX Instruments Technology Ltd");
    VALUES.put(0x1580, "Primex Aerospace Co.");
    VALUES.put(0x1581, "SEH Computertechnik GMBH");
    VALUES.put(0x1582, "Cytec Corporation");
    VALUES.put(0x1583, "Inet Technologies Inc");
    VALUES.put(0x1584, "Vetronix Corporation Engenharia Ltda");
    VALUES.put(0x1585, "Marconi Commerce Systems SRL");
    VALUES.put(0x1586, "Lancast Inc");
    VALUES.put(0x1587, "Konica Corporation");
    VALUES.put(0x1588, "Solidum Systems Corp");
    VALUES.put(0x1589, "Atlantek Microsystems Pty Ltd");
    VALUES.put(0x158A, "Digalog Systems Inc");
    VALUES.put(0x158B, "Allied Data Technologies");
    VALUES.put(0x158C, "Hitachi Semiconductor & Devices Sales Co");
    VALUES.put(0x158D, "Point Multimedia Systems");
    VALUES.put(0x158E, "Lara Technology Inc");
    VALUES.put(0x158F, "Ditect Coop");
    VALUES.put(0x1590, "3pardata Inc.");
    VALUES.put(0x1591, "ARN");
    VALUES.put(0x1592, "Syba Tech Ltd.");
    VALUES.put(0x1593, "Bops Inc");
    VALUES.put(0x1594, "Netgame Ltd");
    VALUES.put(0x1595, "Diva Systems Corp.");
    VALUES.put(0x1596, "Folsom Research Inc");
    VALUES.put(0x1597, "Memec Design Services");
    VALUES.put(0x1598, "Granite Microsystems");
    VALUES.put(0x1599, "Delta Electronics Inc");
    VALUES.put(0x159A, "General Instrument");
    VALUES.put(0x159B, "Faraday Technology Corp");
    VALUES.put(0x159C, "Stratus Computer Systems");
    VALUES.put(0x159D, "Ningbo Harrison Electronics Co Ltd");
    VALUES.put(0x159E, "A-Max Technology Co Ltd");
    VALUES.put(0x159F, "Galea Network Security");
    VALUES.put(0x15A0, "Compumaster SRL");
    VALUES.put(0x15A1, "Geocast Network Systems Inc");
    VALUES.put(0x15A2, "Catalyst Enterprises Inc");
    VALUES.put(0x15A3, "Italtel");
    VALUES.put(0x15A4, "X-Net OY");
    VALUES.put(0x15A5, "Toyota MACS Inc");
    VALUES.put(0x15A6, "Sunlight Ultrasound Technologies Ltd");
    VALUES.put(0x15A7, "SSE Telecom Inc");
    VALUES.put(0x15A8, "Shanghai Communications Technologies Cen");
    VALUES.put(0x15AA, "Moreton Bay");
    VALUES.put(0x15AB, "Bluesteel Networks Inc");
    VALUES.put(0x15AC, "North Atlantic Instruments");
    VALUES.put(0x15AD, "VMware Inc.");
    VALUES.put(0x15AE, "Amersham Pharmacia Biotech");
    VALUES.put(0x15B0, "Zoltrix International Limited");
    VALUES.put(0x15B1, "Source Technology Inc");
    VALUES.put(0x15B2, "Mosaid Technologies Inc.");
    VALUES.put(0x15B3, "Mellanox Technology");
    VALUES.put(0x15B4, "CCI/Triad");
    VALUES.put(0x15B5, "Cimetrics Inc");
    VALUES.put(0x15B6, "Texas Memory Systems Inc");
    VALUES.put(0x15B7, "Sandisk Corp.");
    VALUES.put(0x15B8, "Addi-Data GMBH");
    VALUES.put(0x15B9, "Maestro Digital Communications");
    VALUES.put(0x15BA, "Impacct Technology Corp");
    VALUES.put(0x15BB, "Portwell Inc");
    VALUES.put(0x15BC, "Agilent Technologies");
    VALUES.put(0x15BD, "DFI Inc.");
    VALUES.put(0x15BE, "Sola Electronics");
    VALUES.put(0x15BF, "High Tech Computer Corp (HTC)");
    VALUES.put(0x15C0, "BVM Limited");
    VALUES.put(0x15C1, "Quantel");
    VALUES.put(0x15C2, "Newer Technology Inc");
    VALUES.put(0x15C3, "Taiwan Mycomp Co Ltd");
    VALUES.put(0x15C4, "EVSX Inc");
    VALUES.put(0x15C5, "Procomp Informatics Ltd");
    VALUES.put(0x15C6, "Technical University Of Budapest");
    VALUES.put(0x15C7, "Tateyama System Laboratory Co Ltd");
    VALUES.put(0x15C8, "Penta Media Co. Ltd");
    VALUES.put(0x15C9, "Serome Technology Inc");
    VALUES.put(0x15CA, "Bitboys OY");
    VALUES.put(0x15CB, "AG Electronics Ltd");
    VALUES.put(0x15CC, "Hotrail Inc.");
    VALUES.put(0x15CD, "Dreamtech Co Ltd");
    VALUES.put(0x15CE, "Genrad Inc.");
    VALUES.put(0x15CF, "Hilscher GMBH");
    VALUES.put(0x15D1, "Infineon Technologies AG");
    VALUES.put(0x15D2, "FIC (First International Computer Inc)");
    VALUES.put(0x15D3, "NDS Technologies Israel Ltd");
    VALUES.put(0x15D4, "Iwill Corporation");
    VALUES.put(0x15D5, "Tatung Co.");
    VALUES.put(0x15D6, "Entridia Corporation");
    VALUES.put(0x15D7, "Rockwell-Collins Inc");
    VALUES.put(0x15D8, "Cybernetics Technology Co Ltd");
    VALUES.put(0x15D9, "Super Micro Computer Inc");
    VALUES.put(0x15DA, "Cyberfirm Inc.");
    VALUES.put(0x15DB, "Applied Computing Systems Inc.");
    VALUES.put(0x15DC, "Litronic Inc.");
    VALUES.put(0x15DD, "Sigmatel Inc.");
    VALUES.put(0x15DE, "Malleable Technologies Inc");
    VALUES.put(0x15E0, "Cacheflow Inc");
    VALUES.put(0x15E1, "Voice Technologies Group");
    VALUES.put(0x15E2, "Quicknet Technologies Inc");
    VALUES.put(0x15E3, "Networth Technologies Inc");
    VALUES.put(0x15E4, "VSN Systemen BV");
    VALUES.put(0x15E5, "Valley Technologies Inc");
    VALUES.put(0x15E6, "Agere Inc.");
    VALUES.put(0x15E7, "GET Engineering Corp.");
    VALUES.put(0x15E8, "National Datacomm Corp.");
    VALUES.put(0x15E9, "Pacific Digital Corp.");
    VALUES.put(0x15EA, "Tokyo Denshi Sekei K.K.");
    VALUES.put(0x15EB, "Drsearch GMBH");
    VALUES.put(0x15EC, "Beckhoff Automation GmbH");
    VALUES.put(0x15ED, "Macrolink Inc");
    VALUES.put(0x15EE, "IN Win Development Inc.");
    VALUES.put(0x15EF, "Intelligent Paradigm Inc");
    VALUES.put(0x15F0, "B-Tree Systems Inc");
    VALUES.put(0x15F1, "Times N Systems Inc");
    VALUES.put(0x15F2, "SPOT Imaging Solutions a division of Diagnostic Instruments, Inc");
    VALUES.put(0x15F3, "Digitmedia Corp.");
    VALUES.put(0x15F4, "Valuesoft");
    VALUES.put(0x15F5, "Power Micro Research");
    VALUES.put(0x15F6, "Extreme Packet Device Inc");
    VALUES.put(0x15F7, "Banctec");
    VALUES.put(0x15F8, "Koga Electronics Co");
    VALUES.put(0x15F9, "Zenith Electronics Co");
    VALUES.put(0x15FA, "Axzam Corporation");
    VALUES.put(0x15FB, "Zilog Inc.");
    VALUES.put(0x15FC, "Techsan Electronics Co Ltd");
    VALUES.put(0x15FD, "N-Cubed.Net");
    VALUES.put(0x15FE, "Kinpo Electronics Inc");
    VALUES.put(0x15FF, "Fastpoint Technologies Inc.");
    VALUES.put(0x1600, "Northrop Grumman - Canada Ltd");
    VALUES.put(0x1601, "Tenta Technology");
    VALUES.put(0x1602, "Prosys-TEC Inc.");
    VALUES.put(0x1603, "Nokia Wireless Business Communications");
    VALUES.put(0x1604, "Central System Research Co Ltd");
    VALUES.put(0x1605, "Pairgain Technologies");
    VALUES.put(0x1606, "Europop AG");
    VALUES.put(0x1607, "Lava Semiconductor Manufacturing Inc.");
    VALUES.put(0x1608, "Automated Wagering International");
    VALUES.put(0x1609, "Sciemetric Instruments Inc");
    VALUES.put(0x160A, "Kollmorgen Servotronix");
    VALUES.put(0x160B, "Onkyo Corp.");
    VALUES.put(0x160C, "Oregon Micro Systems Inc.");
    VALUES.put(0x160D, "Aaeon Electronics Inc");
    VALUES.put(0x160E, "CML Emergency Services");
    VALUES.put(0x160F, "ITEC Co Ltd");
    VALUES.put(0x1610, "Tottori Sanyo Electric Co Ltd");
    VALUES.put(0x1611, "Bel Fuse Inc.");
    VALUES.put(0x1612, "Telesynergy Research Inc.");
    VALUES.put(0x1613, "System Craft Inc.");
    VALUES.put(0x1614, "Jace Tech Inc.");
    VALUES.put(0x1615, "Equus Computer Systems Inc");
    VALUES.put(0x1616, "Iotech Inc.");
    VALUES.put(0x1617, "Rapidstream Inc");
    VALUES.put(0x1618, "Esec SA");
    VALUES.put(0x1619, "FarSite Communications Limited");
    VALUES.put(0x161B, "Mobilian Israel Ltd");
    VALUES.put(0x161C, "Berkshire Products");
    VALUES.put(0x161D, "Gatec");
    VALUES.put(0x161E, "Kyoei Sangyo Co Ltd");
    VALUES.put(0x161F, "Arima Computer Corporation");
    VALUES.put(0x1620, "Sigmacom Co Ltd");
    VALUES.put(0x1621, "Lynx Studio Technology Inc");
    VALUES.put(0x1622, "Nokia Home Communications");
    VALUES.put(0x1623, "KRF Tech Ltd");
    VALUES.put(0x1624, "CE Infosys GMBH");
    VALUES.put(0x1625, "Warp Nine Engineering");
    VALUES.put(0x1626, "TDK Semiconductor Corp.");
    VALUES.put(0x1627, "BCom Electronics Inc");
    VALUES.put(0x1629, "Kongsberg Spacetec a.s.");
    VALUES.put(0x162A, "Sejin Computerland Co Ltd");
    VALUES.put(0x162B, "Shanghai Bell Company Limited");
    VALUES.put(0x162C, "C&H Technologies Inc");
    VALUES.put(0x162D, "Reprosoft Co Ltd");
    VALUES.put(0x162E, "Margi Systems Inc");
    VALUES.put(0x162F, "Rohde & Schwarz GMBH & Co KG");
    VALUES.put(0x1630, "Sky Computers Inc");
    VALUES.put(0x1631, "NEC Computer International");
    VALUES.put(0x1632, "Verisys Inc");
    VALUES.put(0x1633, "Adac Corporation");
    VALUES.put(0x1634, "Visionglobal Network Corp.");
    VALUES.put(0x1635, "Decros / S.ICZ a.s.");
    VALUES.put(0x1636, "Jean Company Ltd");
    VALUES.put(0x1637, "NSI");
    VALUES.put(0x1638, "Eumitcom Technology Inc");
    VALUES.put(0x163A, "Air Prime Inc");
    VALUES.put(0x163B, "Glotrex Co Ltd");
    VALUES.put(0x163C, "intel");
    VALUES.put(0x163D, "Heidelberg Digital LLC");
    VALUES.put(0x163E, "3dpower");
    VALUES.put(0x163F, "Renishaw PLC");
    VALUES.put(0x1640, "Intelliworxx Inc");
    VALUES.put(0x1641, "MKNet Corporation");
    VALUES.put(0x1642, "Bitland");
    VALUES.put(0x1643, "Hajime Industries Ltd");
    VALUES.put(0x1644, "Western Avionics Ltd");
    VALUES.put(0x1645, "Quick-Serv. Computer Co. Ltd");
    VALUES.put(0x1646, "Nippon Systemware Co Ltd");
    VALUES.put(0x1647, "Hertz Systemtechnik GMBH");
    VALUES.put(0x1648, "MeltDown Systems LLC");
    VALUES.put(0x1649, "Jupiter Systems");
    VALUES.put(0x164A, "Aiwa Co. Ltd");
    VALUES.put(0x164C, "Department Of Defense");
    VALUES.put(0x164D, "Ishoni Networks");
    VALUES.put(0x164E, "Micrel Inc.");
    VALUES.put(0x164F, "Datavoice (Pty) Ltd.");
    VALUES.put(0x1650, "Admore Technology Inc.");
    VALUES.put(0x1651, "Chaparral Network Storage");
    VALUES.put(0x1652, "Spectrum Digital Inc.");
    VALUES.put(0x1653, "Nature Worldwide Technology Corp");
    VALUES.put(0x1654, "Sonicwall Inc");
    VALUES.put(0x1655, "Dazzle Multimedia Inc.");
    VALUES.put(0x1656, "Insyde Software Corp");
    VALUES.put(0x1657, "Brocade Communications Systems");
    VALUES.put(0x1658, "Med Associates Inc.");
    VALUES.put(0x1659, "Shiba Denshi Systems Inc.");
    VALUES.put(0x165A, "Epix Inc.");
    VALUES.put(0x165B, "Real-Time Digital Inc.");
    VALUES.put(0x165C, "Kondo Kagaku");
    VALUES.put(0x165D, "Hsing Tech. Enterprise Co. Ltd.");
    VALUES.put(0x165E, "Hyunju Computer Co. Ltd.");
    VALUES.put(0x165F, "Comartsystem Korea");
    VALUES.put(0x1660, "Network Security Technologies Inc. (NetSec)");
    VALUES.put(0x1661, "Worldspace Corp.");
    VALUES.put(0x1662, "Int Labs");
    VALUES.put(0x1663, "Elmec Inc. Ltd.");
    VALUES.put(0x1664, "Fastfame Technology Co. Ltd.");
    VALUES.put(0x1665, "Edax Inc.");
    VALUES.put(0x1666, "Norpak Corporation");
    VALUES.put(0x1667, "CoSystems Inc.");
    VALUES.put(0x1668, "Actiontec Electronics Inc.");
    VALUES.put(0x166A, "Komatsu Ltd.");
    VALUES.put(0x166B, "Supernet Inc.");
    VALUES.put(0x166C, "Shade Ltd.");
    VALUES.put(0x166D, "Sibyte Inc.");
    VALUES.put(0x166E, "Schneider Automation Inc.");
    VALUES.put(0x166F, "Televox Software Inc.");
    VALUES.put(0x1670, "Rearden Steel");
    VALUES.put(0x1671, "Atan Technology Inc.");
    VALUES.put(0x1672, "Unitec Co. Ltd.");
    VALUES.put(0x1673, "pctel");
    VALUES.put(0x1675, "Square Wave Technology");
    VALUES.put(0x1676, "Emachines Inc.");
    VALUES.put(0x1677, "Bernecker + Rainer");
    VALUES.put(0x1678, "INH Semiconductor");
    VALUES.put(0x1679, "Tokyo Electron Device Ltd.");
    VALUES.put(0x167F, "iba AG");
    VALUES.put(0x1680, "Dunti Corp.");
    VALUES.put(0x1681, "Hercules");
    VALUES.put(0x1682, "PINE Technology, Ltd.");
    VALUES.put(0x1688, "CastleNet Technology Inc.");
    VALUES.put(0x168A, "Utimaco Safeware AG");
    VALUES.put(0x168B, "Circut Assembly Corp.");
    VALUES.put(0x168C, "Atheros Communications Inc.");
    VALUES.put(0x168D, "NMI Electronics Ltd.");
    VALUES.put(0x168E, "Hyundai MultiCAV Computer Co. Ltd.");
    VALUES.put(0x168F, "KDS Innotech Corp.");
    VALUES.put(0x1690, "NetContinuum, Inc.");
    VALUES.put(0x1693, "FERMA");
    VALUES.put(0x1695, "EPoX Computer Co., Ltd.");
    VALUES.put(0x16AE, "SafeNet Inc.");
    VALUES.put(0x16B3, "CNF Mobile Solutions");
    VALUES.put(0x16B8, "Sonnet Technologies, Inc.");
    VALUES.put(0x16CA, "Cenatek Inc.");
    VALUES.put(0x16CB, "Minolta Co. Ltd.");
    VALUES.put(0x16CC, "Inari Inc.");
    VALUES.put(0x16D0, "Systemax");
    VALUES.put(0x16E0, "Third Millenium Test Solutions, Inc.");
    VALUES.put(0x16E5, "Intellon Corporation");
    VALUES.put(0x16EC, "U.S. Robotics");
    VALUES.put(0x16F0, "LaserLinc Inc.");
    VALUES.put(0x16F1, "Adicti Corp.");
    VALUES.put(0x16F3, "Jetway Information Co., Ltd");
    VALUES.put(0x16F6, "VideoTele.com Inc.");
    VALUES.put(0x1700, "Antara LLC");
    VALUES.put(0x1701, "Interactive Computer Products Inc.");
    VALUES.put(0x1702, "Internet Machines Corp.");
    VALUES.put(0x1703, "Desana Systems");
    VALUES.put(0x1704, "Clearwater Networks");
    VALUES.put(0x1705, "Digital First");
    VALUES.put(0x1706, "Pacific Broadband Communications");
    VALUES.put(0x1707, "Cogency Semiconductor Inc.");
    VALUES.put(0x1708, "Harris Corp.");
    VALUES.put(0x1709, "Zarlink Semiconductor");
    VALUES.put(0x170A, "Alpine Electronics Inc.");
    VALUES.put(0x170B, "NetOctave Inc.");
    VALUES.put(0x170C, "YottaYotta Inc.");
    VALUES.put(0x170D, "SensoMotoric Instruments GmbH");
    VALUES.put(0x170E, "San Valley Systems, Inc.");
    VALUES.put(0x170F, "Cyberdyne Inc.");
    VALUES.put(0x1710, "Pelago Networks");
    VALUES.put(0x1711, "MyName Technologies, Inc.");
    VALUES.put(0x1712, "NICE Systems Inc.");
    VALUES.put(0x1713, "TOPCON Corp.");
    VALUES.put(0x1725, "Vitesse Semiconductor");
    VALUES.put(0x1734, "Fujitsu-Siemens Computers GmbH");
    VALUES.put(0x1737, "LinkSys");
    VALUES.put(0x173B, "Altima Communications Inc.");
    VALUES.put(0x1743, "Peppercon AG");
    VALUES.put(0x174B, "PC Partner Limited");
    VALUES.put(0x1752, "Global Brands Manufacture Ltd.");
    VALUES.put(0x1753, "TeraRecon, Inc.");
    VALUES.put(0x1755, "Alchemy Semiconductor Inc.");
    VALUES.put(0x176A, "General Dynamics Canada");
    VALUES.put(0x1775, "General Electric");
    VALUES.put(0x1789, "Ennyah Technologies Corp");
    VALUES.put(0x1793, "Unitech Electronics Co., Ltd");
    VALUES.put(0x17A1, "Tascorp");
    VALUES.put(0x17A7, "Start Network Technology Co., Ltd.");
    VALUES.put(0x17AA, "Legend Ltd. (Beijing)");
    VALUES.put(0x17AB, "Phillips Components");
    VALUES.put(0x17AF, "Hightech Information Systems, Ltd.");
    VALUES.put(0x17BE, "Philips Semiconductors");
    VALUES.put(0x17C0, "Wistron Corp.");
    VALUES.put(0x17C4, "Movita");
    VALUES.put(0x17CC, "NetChip");
    VALUES.put(0x17cd, "Cadence Design Systems");
    VALUES.put(0x17D5, "Neterion Inc.");
    VALUES.put(0x17db, "Cray, Inc.");
    VALUES.put(0x17E9, "DH electronics GmbH / Sabrent");
    VALUES.put(0x17EE, "Connect Components, Ltd.");
    VALUES.put(0x17F3, "RDC Semiconductor Co., Ltd.");
    VALUES.put(0x17FE, "INPROCOMM");
    VALUES.put(0x1813, "Ambient Technologies Inc");
    VALUES.put(0x1814, "Ralink Technology, Corp.");
    VALUES.put(0x1815, "devolo AG");
    VALUES.put(0x1820, "InfiniCon Systems, Inc.");
    VALUES.put(0x1824, "Avocent");
    VALUES.put(0x1841, "Panda Platinum");
    VALUES.put(0x1860, "Primagraphics Ltd.");
    VALUES.put(0x186C, "Humusoft S.R.O");
    VALUES.put(0x1887, "Elan Digital Systems Ltd");
    VALUES.put(0x1888, "Varisys Limited");
    VALUES.put(0x188D, "Millogic Ltd.");
    VALUES.put(0x1890, "Egenera, Inc.");
    VALUES.put(0x18BC, "Info-Tek Corp.");
    VALUES.put(0x18C9, "ARVOO Engineering BV");
    VALUES.put(0x18CA, "XGI Technology Inc");
    VALUES.put(0x18F1, "Spectrum Systementwicklung Microelectronic GmbH");
    VALUES.put(0x18F4, "Napatech A/S");
    VALUES.put(0x18F7, "Commtech, Inc.");
    VALUES.put(0x18FB, "Resilience Corporation");
    VALUES.put(0x1904, "Ritmo");
    VALUES.put(0x1905, "WIS Technology, Inc.");
    VALUES.put(0x1910, "Seaway Networks");
    VALUES.put(0x1912, "Renesas Electronics");
    VALUES.put(0x1931, "Option NV");
    VALUES.put(0x1941, "Stelar");
    VALUES.put(0x1954, "One Stop Systems, Inc.");
    VALUES.put(0x1969, "Atheros Communications");
    VALUES.put(0x1971, "AGEIA Technologies, Inc.");
    VALUES.put(0x197B, "JMicron Technology Corp.");
    VALUES.put(0x198a, "Nallatech");
    VALUES.put(0x1991, "Topstar Digital Technologies Co., Ltd.");
    VALUES.put(0x19a2, "ServerEngines");
    VALUES.put(0x19A8, "DAQDATA GmbH");
    VALUES.put(0x19AC, "Kasten Chase Applied Research");
    VALUES.put(0x19B6, "Mikrotik");
    VALUES.put(0x19E2, "Vector Informatik GmbH");
    VALUES.put(0x19E3, "DDRdrive LLC");
    VALUES.put(0x1A08, "Linux Networx");
    VALUES.put(0x1a41, "Tilera Corporation");
    VALUES.put(0x1A42, "Imaginant");
    VALUES.put(0x1B13, "Jaton Corporation USA");
    VALUES.put(0x1B21, "Asustek - ASMedia Technology Inc.");
    VALUES.put(0x1B6F, "Etron");
    VALUES.put(0x1B73, "Fresco Logic Inc.");
    VALUES.put(0x1B91, "Averna");
    VALUES.put(0x1BAD, "ReFLEX CES");
    VALUES.put(0x1C0F, "Monarch Innovative Technologies Pvt Ltd's");
    VALUES.put(0x1C32, "Highland Technology, Inc.");
    VALUES.put(0x1c39, "Thomson Video Networks");
    VALUES.put(0x1DE1, "Tekram");
    VALUES.put(0x1FCF, "Miranda Technologies Ltd.");
    VALUES.put(0x2001, "Temporal Research Ltd");
    VALUES.put(0x2646, "Kingston Technology Co.");
    VALUES.put(0x270F, "ChainTek Computer Co. Ltd.");
    VALUES.put(0x2EC1, "Zenic Inc");
    VALUES.put(0x3388, "Hint Corp.");
    VALUES.put(0x3411, "Quantum Designs (H.K.) Inc.");
    VALUES.put(0x3513, "ARCOM Control Systems Ltd.");
    VALUES.put(0x38EF, "4links");
    VALUES.put(0x3D3D, "3Dlabs, Inc. Ltd");
    VALUES.put(0x4005, "Avance Logic Inc.");
    VALUES.put(0x4144, "Alpha Data");
    VALUES.put(0x416C, "Aladdin Knowledge Systems");
    VALUES.put(0x4348, "wch.cn");
    VALUES.put(0x4680, "UMAX Computer Corp.");
    VALUES.put(0x4843, "Hercules Computer Technology");
    VALUES.put(0x4943, "Growth Networks");
    VALUES.put(0x4954, "Integral Technologies");
    VALUES.put(0x4978, "Axil Computer Inc.");
    VALUES.put(0x4C48, "Lung Hwa Electronics");
    VALUES.put(0x4C53, "SBS-OR Industrial Computers");
    VALUES.put(0x4CA1, "Seanix Technology Inc");
    VALUES.put(0x4D51, "Mediaq Inc.");
    VALUES.put(0x4D54, "Microtechnica Co Ltd");
    VALUES.put(0x4DDC, "ILC Data Device Corp.");
    VALUES.put(0x5053, "TBS/Voyetra Technologies");
    VALUES.put(0x508A, "Samsung T10 MP3 Player");
    VALUES.put(0x5136, "S S Technologies");
    VALUES.put(0x5143, "Qualcomm Inc. USA");
    VALUES.put(0x5333, "S3 Graphics Co., Ltd");
    VALUES.put(0x544C, "Teralogic Inc");
    VALUES.put(0x5555, "Genroco Inc.");
    VALUES.put(0x5853, "Citrix Systems, Inc.");
    VALUES.put(0x6409, "Logitec Corp.");
    VALUES.put(0x6666, "Decision Computer International Co.");
    VALUES.put(0x6945, "ASMedia Technology Inc.");
    VALUES.put(0x7604, "O.N. Electric Co. Ltd.");
    VALUES.put(0x7d1, "D-Link Corporation");
    VALUES.put(0x8080, "Xirlink, Inc");
    VALUES.put(0x8086, "Intel Corporation");
    VALUES.put(0x8087, "Intel");
    VALUES.put(0x80EE, "Oracle Corporation - InnoTek Systemberatung GmbH");
    VALUES.put(0x8866, "T-Square Design Inc.");
    VALUES.put(0x8888, "Silicon Magic");
    VALUES.put(0x8E0E, "Computone Corporation");
    VALUES.put(0x9004, "Adaptec Inc");
    VALUES.put(0x9005, "Adaptec Inc");
    VALUES.put(0x919A, "Gigapixel Corp");
    VALUES.put(0x9412, "Holtek");
    VALUES.put(0x9699, "Omni Media Technology Inc.");
    VALUES.put(0x9710, "MosChip Semiconductor Technology");
    VALUES.put(0x9902, "StarGen, Inc.");
    VALUES.put(0xA0A0, "Aopen Inc.");
    VALUES.put(0xA0F1, "Unisys Corporation");
    VALUES.put(0xA200, "NEC Corp.");
    VALUES.put(0xA259, "Hewlett Packard");
    VALUES.put(0xA304, "Sony");
    VALUES.put(0xA727, "3com Corporation");
    VALUES.put(0xAA42, "Abekas, Inc");
    VALUES.put(0xAC1E, "Digital Receiver Technology Inc");
    VALUES.put(0xB1B3, "Shiva Europe Ltd.");
    VALUES.put(0xB894, "Brown & Sharpe Mfg. Co.");
    VALUES.put(0xBEEF, "Mindstream Computing");
    VALUES.put(0xC001, "TSI Telsys");
    VALUES.put(0xC0A9, "Micron/Crucial Technology");
    VALUES.put(0xC0DE, "Motorola");
    VALUES.put(0xC0FE, "Motion Engineering Inc.");
    VALUES.put(0xC622, "Hudson Soft Co Ltd");
    VALUES.put(0xCA50, "Varian, Inc");
    VALUES.put(0xCAFE, "Chrysalis-ITS");
    VALUES.put(0xCCCC, "Catapult Communications");
    VALUES.put(0xD4D4, "Curtiss-Wright Controls Embedded Computing");
    VALUES.put(0xDC93, "Dawicontrol");
    VALUES.put(0xDEAD, "Indigita Corporation");
    VALUES.put(0xDEAF, "Middle Digital, Inc");
    VALUES.put(0xE159, "Tiger Jet Network Inc");
    VALUES.put(0xE4BF, "EKF Elektronik GMBH");
    VALUES.put(0xEA01, "Eagle Technology");
    VALUES.put(0xEABB, "Aashima Technology B.V.");
    VALUES.put(0xEACE, "Endace Measurement Systems Ltd.");
    VALUES.put(0xECC0, "Echo Digital Audio Corporation");
    VALUES.put(0xEDD8, "ARK Logic, Inc");
    VALUES.put(0xF5F5, "F5 Networks Inc.");
    VALUES.put(0xFA57, "Interagon AS");
  }

}
